export let TRIPS = [
  {
    id: 1,
    name: "Agrovet Calourada",
    price_adult: 50,
    price_child: 45,
    time: "20:00h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Entradas:",
    thumb: "assets/img/trip/thumb/festa1.jpg",
    description: "A melhor Calourada do Estado.",
    location: "Chacara Modelo",
    images: [
      "assets/img/trip/thumb/festa1.jpg",
      "assets/img/trip/thumb/festa3.jpg",
      "assets/img/trip/thumb/festa4.jpg",
      "assets/img/trip/thumb/festa2.jpg",
    ],
    highlights: [
      "Ambiente Climatizado",
      "Cerveja Gelada",
      "Musica de Qualidade",
      "Neymar no camarote",
      "Bruna tambem",
    ]
  },
  {
    id: 2,
    name: "Aldair Playboy",
    price_adult: 90,
    price_child: 85,
    time: "00:00h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Entradas:",
    thumb: "assets/img/trip/thumb/festa2.jpg",
    description: "Melhor Som da sofrência Brasileira.",
    location: "Hotel Comfort",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "Mc Don Juan",
    price_adult: 30,
    price_child: 25,
    time: "18:00h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Entradas:",
    thumb: "assets/img/trip/thumb/festa3.jpg",
    description: "O MC do momento está no Acre.",
    location: "Boate Apache",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "Calourada de SI",
    price_adult: 100,
    price_child: 90,
    time: "20:00h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "Entradas:",
    thumb: "assets/img/trip/thumb/festa4.jpg",
    description: "A primeira calourada de SI do Estado.",
    location: "Maison Borges",
    images: [],
    highlights: []
  }
]
